export const patients = [
  {
    patientId: "001",
    symptoms: ["Cough", "Fever", "Difficulty breathing"],
    diagnosis: "COVID-19",
    contactNumber: "+1 123 456 7890",
    email: "johndoe@example.com",
    dateOfBirth: "1990-01-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "002",
    symptoms: ["Headache", "Dizziness"],
    diagnosis: "Migraine",
    contactNumber: "+1 234 567 8901",
    email: "janedoe@example.com",
    dateOfBirth: "1985-02-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "003",
    symptoms: ["Chest pain", "Shortness of breath"],
    diagnosis: "Heart attack",
    contactNumber: "+1 345 678 9012",
    email: "jacksmith@example.com",
    dateOfBirth: "1975-03-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "004",
    symptoms: ["Fatigue", "Joint pain"],
    diagnosis: "Rheumatoid arthritis",
    contactNumber: "+1 456 789 0123",
    email: "janesmith@example.com",
    dateOfBirth: "1980-04-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "005",
    symptoms: ["Abdominal pain", "Nausea", "Vomiting"],
    diagnosis: "Gastroenteritis",
    contactNumber: "+1 567 890 1234",
    email: "johndoe2@example.com",
    dateOfBirth: "1995-05-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "006",
    symptoms: ["Back pain", "Numbness"],
    diagnosis: "Herniated disc",
    contactNumber: "+1 678 901 2345",
    email: "janedoe2@example.com",
    dateOfBirth: "1988-06-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "007",
    symptoms: ["Fever", "Sore throat", "Runny nose"],
    diagnosis: "Common cold",
    contactNumber: "+1 789 012 3456",
    email: "jacksmith2@example.com",
    dateOfBirth: "1979-07-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "008",
    symptoms: ["Chest pain", "Difficulty swallowing"],
    diagnosis: "Esophagitis",
    contactNumber: "+1 890 123 4567",
    email: "janesmith2@example.com",
    dateOfBirth: "1984-08-01",
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    patientId: "009",
    symptoms: ["Mood swings", "Insomnia"],
    diagnosis: "Bipolar disorder",
    contactNumber: "+1 901 234 5678",
    email: "johnsmith@example.com",
    dateOfBirth: "1983-09-01",
    imageUrl: "https://via.placeholder.com/150",
  },
];
